### ISSUE TITLE
Cannot conda build with hdf5, Unsatisfiable dependencies

### ISSUE THREAD

**Issue by jamesp** [AnacondaRecipes/hdf5-feedstock#3]
In the last few weeks (unsure specifically when) a recipe that previously built, is now failing.  I think I've isolated the issue down to hdf5 dependency which, if I'm reading this right, is incompatible with all compilers?

This recipe below fails to build (full stack trace at the bottom of this issue).  Am I doing something obviously wrong?

File `~/conda-recipes/my_test/meta.yml`:
```
package:
  name: my_test
  version: 1

requirements:
  build:
    - cmake
    - make
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - hdf5
```

This is failing to build in several different environments, but i've isolated the issue using the conda-forge docker instance
```
$ docker run --rm -it   -v ~/conda-recipes/:/conda-recipes quay.io/condaforge/linux-anvil-comp7:latest bash
# in the container...

# remove conda-forge from the channel list
$ sed -i "s/- conda-forge//" .condarc
$ conda create -n builder conda conda-build
$ conda activate builder
$ conda build /conda-recipes/my_test/
```

<details>
<summary>Full conda build stack trace</summary>
<pre>
[conda@bcb804dc7a53 ~]$ conda build /conda-recipes/recipes/test_basic/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for my_test
INFO:conda_build.metadata:Attempting to finalize metadata for my_test
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                            

Leaving build/test directories:
  Work:
 /opt/conda/conda-bld/work 
  Test:
 /opt/conda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /opt/conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl 
  Build:
source activate  /opt/conda/conda-bld/_build_env 

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/conda_build/environ.py", line 802, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/opt/conda/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/opt/conda/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/opt/conda/lib/python3.8/site-packages/conda/core/solve.py", line 281, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/conda/core/solve.py", line 815, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/opt/conda/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 1322, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/opt/conda/lib/python3.8/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
libgcc-ng[version='>=9.3.0']
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0']
hdf5 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']

Package libgfortran-ng conflicts for:
libgfortran-ng
hdf5 -> libgfortran-ng[version='>=7,<8.0a0|>=7.2.0,<8.0a0']

Package libstdcxx-ng conflicts for:
hdf5 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
libstdcxx-ng[version='>=9.3.0']
python=3.8 -> libffi[version='>=3.2.1,<3.3a0'] -> libstdcxx-ng[version='>=7.2.0']
python=3.8 -> libstdcxx-ng[version='>=7.3.0']

Package zlib conflicts for:
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0']
hdf5 -> zlib[version='1.2.*|>=1.2.11,<1.3.0a0']

Package libgfortran5 conflicts for:
libgfortran5[version='>=9.3.0']
libgfortran-ng -> libgfortran5[version='8.4.0.*|9.3.0.*']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2031, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 789, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/opt/conda/lib/python3.8/site-packages/conda_build/metadata.py", line 2115, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/metadata.py", line 776, in finalize_outputs_pass
    fm = finalize_metadata(om, parent_metadata=parent_metadata,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 547, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(m,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 409, in add_upstream_pins
    host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
  File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 374, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/render.py", line 139, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/environ.py", line 804, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"libgcc-ng[version='>=7.3.0|>=7.5.0']", "libstdcxx-ng[version='>=7.3.0']", "libgcc-ng[version='>=7.2.0|>=7.3.0']", "libgfortran5[version='8.4.0.*|9.3.0.*']", "zlib[version='>=1.2.11,<1.3.0a0']", "zlib[version='1.2.*|>=1.2.11,<1.3.0a0']", "libgcc-ng[version='>=7.2.0']", "libgfortran-ng[version='>=7,<8.0a0|>=7.2.0,<8.0a0']", "libstdcxx-ng[version='>=7.2.0']", "libstdcxx-ng[version='>=7.2.0|>=7.3.0']"}
[conda@bcb804dc7a53 ~]$ 
</pre>
</details>

**Comment by jamesp** [comment]
Hi @chenghlee, apologies for the direct @ but you've been very helpful in the past! 

Is this the right place to raise this issue or should I be posting it elsewhere?  

I've just tried the example above again and it still fails (tested on both the conda-forge builder docker container, and continuumio/miniconda and both fail to resolve).

**Comment by jamesp** [comment]
A more simple, reproducible version of the incompatibility is to try and create a new environment with hdf5 and gfortran5:

```
$ conda create -n test hdf5 libgfortran5
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package libgfortran-ng conflicts for:
hdf5 -> libgfortran-ng[version='>=7,<8.0a0|>=7.2.0,<8.0a0']
libgfortran5 -> libgfortran-ng[version='8.4.0|9.3.0',build=*_17]
Package zlib conflicts for:
hdf5 -> zlib[version='1.2.*,>=1.2.11,<1.3.0a0|>=1.2.11,<1.3.0a0']
Package libgcc-ng conflicts for:
hdf5 -> libgcc-ng[version='>=7.2.0|>=7.3.0']
Package libstdcxx-ng conflicts for:
hdf5 -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
```

**Comment by chenghlee** [comment]
@jamesp: this is right place to raise such issues.

I suspect the conflicts you're seeing have to do with the newer GCC and associated runtime library packages on defaults requiring at least glibc 2.17 (CentOS 7). Can you please tell me what version of conda and conda-build you're using (i.e., output from `conda info`)?

**Comment by jamesp** [comment]
Super, thanks.

This is the environment using `continuumio/miniconda3:latest` docker image:

```
(builder) root@08bb09eb4dd3:/# conda info

     active environment : builder
    active env location : /opt/conda/envs/builder
            shell level : 2
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/4.14.231-173.361.amzn2.x86_64 debian/10 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False

(builder) root@08bb09eb4dd3:/# conda list
# packages in environment at /opt/conda/envs/builder:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
beautifulsoup4            4.9.3              pyha847dfd_0  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.7.5             h06a4308_1  
certifi                   2021.5.30        py39h06a4308_0  
cffi                      1.14.6           py39h400218f_0  
chardet                   4.0.0           py39h06a4308_1003  
conda                     4.10.3           py39h06a4308_0  
conda-build               3.21.4           py39h06a4308_0  
conda-package-handling    1.7.3            py39h27cfd23_1  
cryptography              3.4.7            py39hd23ed53_0  
filelock                  3.0.12             pyhd3eb1b0_1  
glob2                     0.7                pyhd3eb1b0_0  
icu                       58.2                 he6710b0_3  
idna                      2.10               pyhd3eb1b0_0  
jinja2                    3.0.1              pyhd3eb1b0_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libarchive                3.4.2                h62408e4_0  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
liblief                   0.10.1               h2531618_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libxml2                   2.9.12               h03d6c58_0  
lz4-c                     1.9.3                h2531618_0  
markupsafe                2.0.1            py39h27cfd23_0  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1k               h27cfd23_0  
patchelf                  0.12                 h2531618_1  
pip                       21.1.3           py39h06a4308_0  
pkginfo                   1.7.1            py39h06a4308_0  
psutil                    5.8.0            py39h27cfd23_1  
py-lief                   0.10.1           py39h2531618_1  
pycosat                   0.6.3            py39h27cfd23_0  
pycparser                 2.20                       py_2  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.5                h12debd9_4  
python-libarchive-c       2.9                pyhd3eb1b0_1  
pytz                      2021.1             pyhd3eb1b0_0  
pyyaml                    5.4.1            py39h27cfd23_1  
readline                  8.1                  h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
ripgrep                   12.1.1                        0  
ruamel_yaml               0.15.100         py39h27cfd23_0  
setuptools                52.0.0           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
soupsieve                 2.2.1              pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.61.2             pyhd3eb1b0_1  
tzdata                    2021a                h52ac0ba_0  
urllib3                   1.26.6             pyhd3eb1b0_1  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  
```

edit: apologies, originally this showed the info of a test of the python2.7 environment, which also fails. Python 3 info now.

**Comment by chenghlee** [comment]
What's happening here is that HDF 5 was built using Gfortran 7.x, so there's a hard requirement on libgfortran 4 (via the `libgfortran-ng >=7,<8.0a0` requirement):
```
$ conda search --platform=linux-64 --info 'hdf5'
Loading channels: done
## ... snip to show two most recent releases/builds ...

hdf5 1.10.7 hb1b8bf9_0
----------------------
file name   : hdf5-1.10.7-hb1b8bf9_0.conda
name        : hdf5
version     : 1.10.7
build       : hb1b8bf9_0
build number: 0
size        : 3.8 MB
license     : HDF5
subdir      : linux-64
url         : https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.10.7-hb1b8bf9_0.conda
md5         : 6456dd4919d239fd28bbe34c0d8ed353
timestamp   : 2020-09-17 16:46:43 UTC
dependencies:
  - libgcc-ng >=7.3.0
  - libgfortran-ng >=7,<8.0a0
  - libstdcxx-ng >=7.3.0
  - zlib >=1.2.11,<1.3.0a0


hdf5 1.12.0 hc3cf35f_0
----------------------
file name   : hdf5-1.12.0-hc3cf35f_0.conda
name        : hdf5
version     : 1.12.0
build       : hc3cf35f_0
build number: 0
size        : 4.0 MB
license     : HDF5
subdir      : linux-64
url         : https://repo.anaconda.com/pkgs/main/linux-64/hdf5-1.12.0-hc3cf35f_0.conda
md5         : c6a7ece1edb8b5a6cdc1fba5dc87d8cc
timestamp   : 2021-01-24 19:20:31 UTC
dependencies:
  - libgcc-ng >=7.3.0
  - libgfortran-ng >=7,<8.0a0
  - libstdcxx-ng >=7.3.0
  - zlib >=1.2.11,<1.3.0a0
```

However, the `{{ compiler('fortran') }}` directive in your recipe's `meta.yaml` pulls in the most recent Gfortran release on defaults, which at this time is Gfortran 9.3 and libgfortran 5 ([introduced in GCC 8](https://gcc.gnu.org/gcc-8/changes.html#fortran)). This in turn triggers a dependency conflict with HDF5.

The immediate work around for this is to pin your Fortran compiler dependency to Gfortran 7; e.g., having a recipe conda_build_config.yaml with:
```
fortran_compiler_version:
  - 7.3  # [linux and x86_64] <-- use this if you want to ensure CentOS 6 (glibc >=2.12) compatibility
  - 7.5  # [linux and x86_64] <-- use this if you only care about supporting CentOS 7 or later (glibc >=2.17)
```

In the meantime, I'll work with the Anaconda team to ensure the latest two versions of HDF5 (1.10.7 and 1.12.0) are built with libgfortran 5 support. Note that these updated builds will require CentOS 7 (glibc 2.17) or later.

**Comment by jamesp** [comment]
Many thanks @chenghlee, I'll try rebuilding with the compiler constraint for CentOS 6.
